#!/bin/bash

# Script to generate deployment jobs for all components
# This script generates GitLab CI/CD job definitions for all components

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/gitlab/ci-cd/generated-jobs.yml"

# Component definitions
declare -A CLUSTER_COMPONENTS=(
    ["cilium"]="cilium/cilium"
    ["nginx-ingress"]="ingress-nginx/ingress-nginx"
    ["metallb"]="metallb/metallb"
    ["nfs"]="nfs-subdir-external-provisioner/nfs-subdir-external-provisioner"
)

declare -A MONITORING_COMPONENTS=(
    ["prometheus"]="prometheus-community/kube-prometheus-stack"
    ["grafana"]="grafana/grafana"
    ["loki"]="grafana/loki-stack"
    ["alertmanager"]="prometheus-community/kube-prometheus-stack"
)

declare -A NOVARIDIUM_COMPONENTS=(
    ["postgresql"]="bitnami/postgresql"
    ["minio"]="minio/minio"
    ["milvus"]="milvus/milvus"
    ["airbyte"]="airbyte/airbyte"
    ["flyte"]="flyteorg/flyte-binary"
    ["ollama"]=""
    ["openfga"]=""
    ["openspg"]=""
    ["pgadmin"]=""
    ["novaridium"]=""
    ["discomine"]=""
    ["validator"]=""
    ["chat-mcp"]=""
)

generate_job() {
    local component=$1
    local component_type=$2
    local environment=$3
    local chart_repo=$4
    local namespace=$5
    
    cat <<EOF

# ${component_type^} Component: ${component} - ${environment^}
deploy:${component_type}:${component}:${environment}:
  extends: .deploy-${component_type}-component
  variables:
    COMPONENT: "${component}"
    ENVIRONMENT: "${environment}"
    CHART_REPO: "${chart_repo}"
    NAMESPACE: "${namespace}"
  environment:
    name: ${environment}/${component_type}/${component}
    url: https://${component}.${environment}.example.com
  only:
    - ${([ "$environment" = "dev" ] && echo "develop") || ([ "$environment" = "staging" ] && echo "main") || ([ "$environment" = "production" ] && echo "tags")}
  when: manual
  allow_failure: false
EOF
}

generate_rollback_job() {
    local component=$1
    local component_type=$2
    
    cat <<EOF

# Rollback: ${component_type^} Component - ${component}
rollback:${component_type}:${component}:
  extends: .rollback-base
  variables:
    COMPONENT: "${component}"
    NAMESPACE: "${([ "$component_type" = "cluster" ] && echo "cluster-infra-${component}") || ([ "$component_type" = "monitoring" ] && echo "monitoring") || ([ "$component_type" = "novaridium" ] && echo "novaridium")}"
  environment:
    name: rollback/${component_type}/${component}
    action: rollback
  when: manual
EOF
}

# Generate jobs file
cat > "$OUTPUT_FILE" <<'HEADER'
# Auto-generated deployment jobs
# This file is generated by scripts/generate-deployment-jobs.sh
# DO NOT EDIT MANUALLY - Regenerate using the script

HEADER

# Generate cluster component jobs
echo "# ============================================" >> "$OUTPUT_FILE"
echo "# CLUSTER COMPONENTS" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"

for component in "${!CLUSTER_COMPONENTS[@]}"; do
    chart_repo="${CLUSTER_COMPONENTS[$component]}"
    for env in dev staging production; do
        generate_job "$component" "cluster" "$env" "$chart_repo" "cluster-infra-${component}" >> "$OUTPUT_FILE"
    done
    generate_rollback_job "$component" "cluster" >> "$OUTPUT_FILE"
done

# Generate monitoring component jobs
echo "" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"
echo "# MONITORING COMPONENTS" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"

for component in "${!MONITORING_COMPONENTS[@]}"; do
    chart_repo="${MONITORING_COMPONENTS[$component]}"
    for env in dev staging production; do
        generate_job "$component" "monitoring" "$env" "$chart_repo" "monitoring" >> "$OUTPUT_FILE"
    done
    generate_rollback_job "$component" "monitoring" >> "$OUTPUT_FILE"
done

# Generate novaridium component jobs
echo "" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"
echo "# NOVARIDIUM COMPONENTS" >> "$OUTPUT_FILE"
echo "# ============================================" >> "$OUTPUT_FILE"

for component in "${!NOVARIDIUM_COMPONENTS[@]}"; do
    chart_repo="${NOVARIDIUM_COMPONENTS[$component]}"
    for env in dev staging production; do
        generate_job "$component" "novaridium" "$env" "$chart_repo" "novaridium" >> "$OUTPUT_FILE"
    done
    generate_rollback_job "$component" "novaridium" >> "$OUTPUT_FILE"
done

echo ""
echo "Generated deployment jobs file: $OUTPUT_FILE"
echo "Review the file and include it in your .gitlab-ci.yml if needed"
